---
linux:  # Группа хостов
  children:  # Обозначение, что будет подгруппа хостов
    nginx:  # Имя подгруппы хостов
      hosts:  # Узлы группы
        vm_1:  # Имя машины
          ansible_host: 158.160.180.43  # Адрес машины
        vm_2:  # Имя машины
          ansible_host: 158.160.178.78  # Адрес машины
        vm_3:  # Имя машины
          ansible_host: 158.160.189.20  # Адрес машины
  vars:  # Переменные, доступные или используемые для всех подгрупп
    ansible_user: s1841463  # имя пользователя
    connection_protocol: ssh  # тип подключения
    ansible_become: true  # с другим пользователем после подключения